name: Shell Lint

on: [pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install shellcheck
        run: sudo apt install shellcheck
        
      - name: shellcheck
        run: git show --stat --oneline --name-only HEAD | tail -n +2	|  tr '\n' ','
